//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.SwordSkill
{
/// <summary>
/// 技能前置参数
/// </summary>
public sealed partial class SkillFontValue :  Bright.Config.BeanBase 
{
    public SkillFontValue(ByteBuf _buf) 
    {
        MP = _buf.ReadInt();
        Target = _buf.ReadInt();
        RANGE = _buf.ReadInt();
        Round = _buf.ReadInt();
        PostInit();
    }

    public static SkillFontValue DeserializeSkillFontValue(ByteBuf _buf)
    {
        return new Tb.SwordSkill.SkillFontValue(_buf);
    }

    /// <summary>
    /// MP消耗
    /// </summary>
    public int MP { get; private set; }
    /// <summary>
    /// 目标
    /// </summary>
    public int Target { get; private set; }
    /// <summary>
    /// 范围
    /// </summary>
    public int RANGE { get; private set; }
    /// <summary>
    /// 持续回合
    /// </summary>
    public int Round { get; private set; }

    public const int __ID__ = 1579428491;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MP:" + MP + ","
        + "Target:" + Target + ","
        + "RANGE:" + RANGE + ","
        + "Round:" + Round + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}