//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.enemyModelBase
{
public sealed partial class EnemyModel :  Bright.Config.BeanBase 
{
    public EnemyModel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ResName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Des = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Des.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PassivitySkill = new System.Collections.Generic.List<Tb.EnemyModelBase.SkillValue>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Tb.EnemyModelBase.SkillValue _e0;  _e0 = Tb.EnemyModelBase.SkillValue.DeserializeSkillValue(_buf); PassivitySkill.Add(_e0);}}
        PostInit();
    }

    public static EnemyModel DeserializeEnemyModel(ByteBuf _buf)
    {
        return new enemyModelBase.EnemyModel(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 怪物名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 怪物资源
    /// </summary>
    public string ResName { get; private set; }
    /// <summary>
    /// 属性值
    /// </summary>
    public System.Collections.Generic.List<int> Des { get; private set; }
    /// <summary>
    /// 技能回合参数
    /// </summary>
    public System.Collections.Generic.List<Tb.EnemyModelBase.SkillValue> PassivitySkill { get; private set; }

    public const int __ID__ = 524401949;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in PassivitySkill) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in PassivitySkill) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ResName:" + ResName + ","
        + "Des:" + Bright.Common.StringUtil.CollectionToString(Des) + ","
        + "PassivitySkill:" + Bright.Common.StringUtil.CollectionToString(PassivitySkill) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}