//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.equipmentBase
{
public sealed partial class Equipment :  Bright.Config.BeanBase 
{
    public Equipment(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SlotPos = _buf.ReadInt();
        EquipType = (equipment.EquipmentFlag)_buf.ReadInt();
        BaseAttriBute = Tb.EquipmentBase.BaseArrayEquipBute.DeserializeBaseArrayEquipBute(_buf);
        Attribute = Tb.EquipmentBase.ArrayEquipBute.DeserializeArrayEquipBute(_buf);
        PostInit();
    }

    public static Equipment DeserializeEquipment(ByteBuf _buf)
    {
        return new equipmentBase.Equipment(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 装备位置
    /// </summary>
    public int SlotPos { get; private set; }
    /// <summary>
    /// 装备类型
    /// </summary>
    public equipment.EquipmentFlag EquipType { get; private set; }
    /// <summary>
    /// 装备基础属性
    /// </summary>
    public Tb.EquipmentBase.BaseArrayEquipBute BaseAttriBute { get; private set; }
    /// <summary>
    /// 装备属性
    /// </summary>
    public Tb.EquipmentBase.ArrayEquipBute Attribute { get; private set; }

    public const int __ID__ = -128995393;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        BaseAttriBute?.Resolve(_tables);
        Attribute?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        BaseAttriBute?.TranslateText(translator);
        Attribute?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SlotPos:" + SlotPos + ","
        + "EquipType:" + EquipType + ","
        + "BaseAttriBute:" + BaseAttriBute + ","
        + "Attribute:" + Attribute + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}