//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.equipmentBase
{
   
public partial class TbEquipmentBase
{
    private readonly Dictionary<int, equipmentBase.Equipment> _dataMap;
    private readonly List<equipmentBase.Equipment> _dataList;
    
    public TbEquipmentBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, equipmentBase.Equipment>();
        _dataList = new List<equipmentBase.Equipment>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            equipmentBase.Equipment _v;
            _v = equipmentBase.Equipment.DeserializeEquipment(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, equipmentBase.Equipment> DataMap => _dataMap;
    public List<equipmentBase.Equipment> DataList => _dataList;

    public equipmentBase.Equipment GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public equipmentBase.Equipment Get(int key) => _dataMap[key];
    public equipmentBase.Equipment this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}