//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.SKILL
{ 
    [System.Flags]
    public enum TARGET
    {
        /// <summary>
        /// 全屏
        /// </summary>
        None = 1,
        /// <summary>
        /// 队伍
        /// </summary>
        TEAM = 2,
        /// <summary>
        /// 敌方
        /// </summary>
        ENEMY = 3,
    }

} 
