//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.SKILL
{ 
    [System.Flags]
    public enum TYPE
    {
        /// <summary>
        /// 剑类
        /// </summary>
        SwordType = 1,
        /// <summary>
        /// 近战攻击
        /// </summary>
        Close_Combat = 2,
        /// <summary>
        /// 远程攻击
        /// </summary>
        Ranged_Combat = 3,
        /// <summary>
        /// 魔法攻击
        /// </summary>
        Magic_Attack = 4,
        /// <summary>
        /// 诅咒魔法
        /// </summary>
        Curse = 5,
        /// <summary>
        /// 治疗
        /// </summary>
        CURE = 6,
        /// <summary>
        /// 游戏中权限等级最高的攻击
        /// </summary>
        SUBSIDIARY = 7,
    }

} 
