//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.enemySkillBase
{
   
public partial class TbEnemySkillBase
{
    private readonly Dictionary<int, enemySkillBase.EnemySkill> _dataMap;
    private readonly List<enemySkillBase.EnemySkill> _dataList;
    
    public TbEnemySkillBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, enemySkillBase.EnemySkill>();
        _dataList = new List<enemySkillBase.EnemySkill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            enemySkillBase.EnemySkill _v;
            _v = enemySkillBase.EnemySkill.DeserializeEnemySkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, enemySkillBase.EnemySkill> DataMap => _dataMap;
    public List<enemySkillBase.EnemySkill> DataList => _dataList;

    public enemySkillBase.EnemySkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemySkillBase.EnemySkill Get(int key) => _dataMap[key];
    public enemySkillBase.EnemySkill this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}