//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.item
{
/// <summary>
/// 该Spine动画所有的动画名称
/// </summary>
public sealed partial class ItemTipsDes :  Bright.Config.BeanBase 
{
    public ItemTipsDes(ByteBuf _buf) 
    {
        EffectDes = _buf.ReadString();
        PostInit();
    }

    public static ItemTipsDes DeserializeItemTipsDes(ByteBuf _buf)
    {
        return new item.ItemTipsDes(_buf);
    }

    /// <summary>
    /// 效果描述分段
    /// </summary>
    public string EffectDes { get; private set; }

    public const int __ID__ = 1038890156;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "EffectDes:" + EffectDes + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}