//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.itemBackGround
{ 

public sealed partial class ItemBgGround :  Bright.Config.BeanBase 
{
    public ItemBgGround(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["ItemBoxLine"].IsString) { throw new SerializationException(); }  ItemBoxLine = _json["ItemBoxLine"]; }
        { if(!_json["ItemColor"].IsString) { throw new SerializationException(); }  ItemColor = _json["ItemColor"]; }
        PostInit();
    }

    public ItemBgGround(int id, string ItemBoxLine, string ItemColor ) 
    {
        this.Id = id;
        this.ItemBoxLine = ItemBoxLine;
        this.ItemColor = ItemColor;
        PostInit();
    }

    public static ItemBgGround DeserializeItemBgGround(JSONNode _json)
    {
        return new itemBackGround.ItemBgGround(_json);
    }

    /// <summary>
    /// 品质ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 物品背景线框
    /// </summary>
    public string ItemBoxLine { get; private set; }
    /// <summary>
    /// 物品背景颜色
    /// </summary>
    public string ItemColor { get; private set; }

    public const int __ID__ = -1469461876;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ItemBoxLine:" + ItemBoxLine + ","
        + "ItemColor:" + ItemColor + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
