//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.itemBackGround
{ 

public sealed partial class TbItemBgGround
{
    private readonly Dictionary<int, itemBackGround.ItemBgGround> _dataMap;
    private readonly List<itemBackGround.ItemBgGround> _dataList;
    
    public TbItemBgGround(JSONNode _json)
    {
        _dataMap = new Dictionary<int, itemBackGround.ItemBgGround>();
        _dataList = new List<itemBackGround.ItemBgGround>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = itemBackGround.ItemBgGround.DeserializeItemBgGround(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, itemBackGround.ItemBgGround> DataMap => _dataMap;
    public List<itemBackGround.ItemBgGround> DataList => _dataList;

    public itemBackGround.ItemBgGround GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public itemBackGround.ItemBgGround Get(int key) => _dataMap[key];
    public itemBackGround.ItemBgGround this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}