//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.vFXSkillModelBase
{
   
public partial class TBVFXSkillModelBase
{
    private readonly Dictionary<int, vFXSkillModelBase.VFXSkillModel> _dataMap;
    private readonly List<vFXSkillModelBase.VFXSkillModel> _dataList;
    
    public TBVFXSkillModelBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, vFXSkillModelBase.VFXSkillModel>();
        _dataList = new List<vFXSkillModelBase.VFXSkillModel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            vFXSkillModelBase.VFXSkillModel _v;
            _v = vFXSkillModelBase.VFXSkillModel.DeserializeVFXSkillModel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, vFXSkillModelBase.VFXSkillModel> DataMap => _dataMap;
    public List<vFXSkillModelBase.VFXSkillModel> DataList => _dataList;

    public vFXSkillModelBase.VFXSkillModel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public vFXSkillModelBase.VFXSkillModel Get(int key) => _dataMap[key];
    public vFXSkillModelBase.VFXSkillModel this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}