//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.vFXSkillModelBase
{
public sealed partial class VFXSkillModel :  Bright.Config.BeanBase 
{
    public VFXSkillModel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ResName = _buf.ReadString();
        DealyHit = _buf.ReadFloat();
        ReleaseType = _buf.ReadInt();
        PostInit();
    }

    public static VFXSkillModel DeserializeVFXSkillModel(ByteBuf _buf)
    {
        return new vFXSkillModelBase.VFXSkillModel(_buf);
    }

    /// <summary>
    /// 特效ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 特效资源
    /// </summary>
    public string ResName { get; private set; }
    /// <summary>
    /// 延迟命中参数
    /// </summary>
    public float DealyHit { get; private set; }
    /// <summary>
    /// 释放类型
    /// </summary>
    public int ReleaseType { get; private set; }

    public const int __ID__ = 2012331555;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ResName:" + ResName + ","
        + "DealyHit:" + DealyHit + ","
        + "ReleaseType:" + ReleaseType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}