//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.SwordSkill
{
/// <summary>
/// 列表所有技能属性
/// </summary>
public sealed partial class SkillAttrArray :  Bright.Config.BeanBase 
{
    public SkillAttrArray(ByteBuf _buf) 
    {
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SkillAttrs = new Tb.SwordSkill.SkillAttr[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { Tb.SwordSkill.SkillAttr __e0;__e0 = Tb.SwordSkill.SkillAttr.DeserializeSkillAttr(_buf); SkillAttrs[__index0] = __e0;}}
        PostInit();
    }

    public static SkillAttrArray DeserializeSkillAttrArray(ByteBuf _buf)
    {
        return new Tb.SwordSkill.SkillAttrArray(_buf);
    }

    /// <summary>
    /// 列表技能属性
    /// </summary>
    public Tb.SwordSkill.SkillAttr[] SkillAttrs { get; private set; }

    public const int __ID__ = -1190169839;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in SkillAttrs) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in SkillAttrs) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "SkillAttrs:" + Bright.Common.StringUtil.CollectionToString(SkillAttrs) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}