//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.SwordSkill
{
/// <summary>
/// 技能属性
/// </summary>
public sealed partial class SkillAttr :  Bright.Config.BeanBase 
{
    public SkillAttr(ByteBuf _buf) 
    {
        AttriID = _buf.ReadInt();
        Value = _buf.ReadInt();
        Percent = _buf.ReadInt();
        PostInit();
    }

    public static SkillAttr DeserializeSkillAttr(ByteBuf _buf)
    {
        return new Tb.SwordSkill.SkillAttr(_buf);
    }

    /// <summary>
    /// 属性ID
    /// </summary>
    public int AttriID { get; private set; }
    /// <summary>
    /// 值
    /// </summary>
    public int Value { get; private set; }
    /// <summary>
    /// 是否是百分比
    /// </summary>
    public int Percent { get; private set; }

    public const int __ID__ = 1389160488;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AttriID:" + AttriID + ","
        + "Value:" + Value + ","
        + "Percent:" + Percent + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}