//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.SwordSkill
{
/// <summary>
/// 技能内置参数
/// </summary>
public sealed partial class SkillParamValue :  Bright.Config.BeanBase 
{
    public SkillParamValue(ByteBuf _buf) 
    {
        ATTACKTP = _buf.ReadInt();
        Value = _buf.ReadInt();
        Percent = _buf.ReadBool();
        BUFFID = _buf.ReadInt();
        PostInit();
    }

    public static SkillParamValue DeserializeSkillParamValue(ByteBuf _buf)
    {
        return new Tb.SwordSkill.SkillParamValue(_buf);
    }

    /// <summary>
    /// 属性类型值
    /// </summary>
    public int ATTACKTP { get; private set; }
    /// <summary>
    /// 属性值
    /// </summary>
    public int Value { get; private set; }
    /// <summary>
    /// 是否是百分比
    /// </summary>
    public bool Percent { get; private set; }
    /// <summary>
    /// BuffID
    /// </summary>
    public int BUFFID { get; private set; }

    public const int __ID__ = -1366351397;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ATTACKTP:" + ATTACKTP + ","
        + "Value:" + Value + ","
        + "Percent:" + Percent + ","
        + "BUFFID:" + BUFFID + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}