//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.fightingBase
{
public sealed partial class Fighting :  Bright.Config.BeanBase 
{
    public Fighting(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        AttributeDes = _buf.ReadString();
        PostInit();
    }

    public static Fighting DeserializeFighting(ByteBuf _buf)
    {
        return new fightingBase.Fighting(_buf);
    }

    /// <summary>
    /// 属性ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 属性名
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 属性描述
    /// </summary>
    public string AttributeDes { get; private set; }

    public const int __ID__ = 1329668029;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "AttributeDes:" + AttributeDes + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}