//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.fightingBase
{
   
public partial class TbFightingBase
{
    private readonly Dictionary<int, fightingBase.Fighting> _dataMap;
    private readonly List<fightingBase.Fighting> _dataList;
    
    public TbFightingBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, fightingBase.Fighting>();
        _dataList = new List<fightingBase.Fighting>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            fightingBase.Fighting _v;
            _v = fightingBase.Fighting.DeserializeFighting(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, fightingBase.Fighting> DataMap => _dataMap;
    public List<fightingBase.Fighting> DataList => _dataList;

    public fightingBase.Fighting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public fightingBase.Fighting Get(int key) => _dataMap[key];
    public fightingBase.Fighting this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}