//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.EquipmentBase
{
public sealed partial class BaseArrayEquipBute :  Bright.Config.BeanBase 
{
    public BaseArrayEquipBute(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BaseAttribute = new System.Collections.Generic.List<Tb.EquipmentBase.WeaponAttri>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Tb.EquipmentBase.WeaponAttri _e0;  _e0 = Tb.EquipmentBase.WeaponAttri.DeserializeWeaponAttri(_buf); BaseAttribute.Add(_e0);}}
        PostInit();
    }

    public static BaseArrayEquipBute DeserializeBaseArrayEquipBute(ByteBuf _buf)
    {
        return new Tb.EquipmentBase.BaseArrayEquipBute(_buf);
    }

    /// <summary>
    /// 基本装备属性列表值
    /// </summary>
    public System.Collections.Generic.List<Tb.EquipmentBase.WeaponAttri> BaseAttribute { get; private set; }

    public const int __ID__ = 587518363;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in BaseAttribute) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in BaseAttribute) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "BaseAttribute:" + Bright.Common.StringUtil.CollectionToString(BaseAttribute) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}