//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.EquipmentBase
{
/// <summary>
/// 基本属性
/// </summary>
public sealed partial class WeaponAttri :  Bright.Config.BeanBase 
{
    public WeaponAttri(ByteBuf _buf) 
    {
        AttriID = _buf.ReadInt();
        MixValue = _buf.ReadInt();
        MaxValue = _buf.ReadInt();
        PostInit();
    }

    public static WeaponAttri DeserializeWeaponAttri(ByteBuf _buf)
    {
        return new Tb.EquipmentBase.WeaponAttri(_buf);
    }

    /// <summary>
    /// 属性ID
    /// </summary>
    public int AttriID { get; private set; }
    /// <summary>
    /// 伤害值1
    /// </summary>
    public int MixValue { get; private set; }
    /// <summary>
    /// 伤害值2
    /// </summary>
    public int MaxValue { get; private set; }

    public const int __ID__ = -116536755;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AttriID:" + AttriID + ","
        + "MixValue:" + MixValue + ","
        + "MaxValue:" + MaxValue + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}