//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.EquipmentBase
{
public sealed partial class ArrayEquipBute :  Bright.Config.BeanBase 
{
    public ArrayEquipBute(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MainAttribute = new System.Collections.Generic.List<Tb.EquipmentBase.AttriBute>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Tb.EquipmentBase.AttriBute _e0;  _e0 = Tb.EquipmentBase.AttriBute.DeserializeAttriBute(_buf); MainAttribute.Add(_e0);}}
        PostInit();
    }

    public static ArrayEquipBute DeserializeArrayEquipBute(ByteBuf _buf)
    {
        return new Tb.EquipmentBase.ArrayEquipBute(_buf);
    }

    /// <summary>
    /// 装备列表属性值
    /// </summary>
    public System.Collections.Generic.List<Tb.EquipmentBase.AttriBute> MainAttribute { get; private set; }

    public const int __ID__ = -1864609814;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in MainAttribute) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in MainAttribute) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "MainAttribute:" + Bright.Common.StringUtil.CollectionToString(MainAttribute) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}