//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.ATTACK
{ 
    [System.Flags]
    public enum EFFECT
    {
        /// <summary>
        /// 最大血量百分比或血量增加
        /// </summary>
        HP = 1,
        /// <summary>
        /// 最大法力百分比或法力增加
        /// </summary>
        MP = 2,
        /// <summary>
        /// 近战攻击力
        /// </summary>
        MEATK = 3,
        /// <summary>
        /// 魔法攻击力
        /// </summary>
        MAGATK = 4,
        /// <summary>
        /// 近战防御力
        /// </summary>
        MEDFS = 5,
        /// <summary>
        /// 魔法防御力
        /// </summary>
        MAGDFS = 6,
        /// <summary>
        /// 元素抗性
        /// </summary>
        ELMRES = 7,
        /// <summary>
        /// 诅咒抗性
        /// </summary>
        CURSERES = 8,
        /// <summary>
        /// 物理攻击命中
        /// </summary>
        PHYHIT = 9,
        /// <summary>
        /// 元素命中
        /// </summary>
        ELMHIT = 10,
        /// <summary>
        /// 诅咒命中
        /// </summary>
        CURSEHIT = 11,
        /// <summary>
        /// 魔法穿透
        /// </summary>
        MagicPenetration = 12,
        /// <summary>
        /// 出手速度
        /// </summary>
        SPEED = 13,
        /// <summary>
        /// 暴击
        /// </summary>
        CRITHIT = 14,
        /// <summary>
        /// 强韧
        /// </summary>
        TOUGH = 15,
        /// <summary>
        /// 破甲
        /// </summary>
        ARMRBK = 16,
    }

} 
