//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.ATTACK
{ 
    [System.Flags]
    public enum RANGE
    {
        /// <summary>
        /// 全部范围
        /// </summary>
        ALL = 1,
        /// <summary>
        /// 单人
        /// </summary>
        SOLO = 2,
        /// <summary>
        /// 十字范围
        /// </summary>
        CROSS = 3,
    }

} 
