//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.initialRoleAttrieBase
{
public sealed partial class InitialRoleAttrie :  Bright.Config.BeanBase 
{
    public InitialRoleAttrie(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Mp = _buf.ReadInt();
        MaxHp = _buf.ReadInt();
        MaxMp = _buf.ReadInt();
        EleMagicHit = _buf.ReadInt();
        CurseMagicHit = _buf.ReadInt();
        PostInit();
    }

    public static InitialRoleAttrie DeserializeInitialRoleAttrie(ByteBuf _buf)
    {
        return new initialRoleAttrieBase.InitialRoleAttrie(_buf);
    }

    /// <summary>
    /// 职业ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 生命
    /// </summary>
    public int Hp { get; private set; }
    /// <summary>
    /// 法力值
    /// </summary>
    public int Mp { get; private set; }
    /// <summary>
    /// 最大生命值
    /// </summary>
    public int MaxHp { get; private set; }
    /// <summary>
    /// 最大法力值
    /// </summary>
    public int MaxMp { get; private set; }
    /// <summary>
    /// 元素魔法命中
    /// </summary>
    public int EleMagicHit { get; private set; }
    /// <summary>
    /// 诅咒魔法命中
    /// </summary>
    public int CurseMagicHit { get; private set; }

    public const int __ID__ = -2141956751;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Hp:" + Hp + ","
        + "Mp:" + Mp + ","
        + "MaxHp:" + MaxHp + ","
        + "MaxMp:" + MaxMp + ","
        + "EleMagicHit:" + EleMagicHit + ","
        + "CurseMagicHit:" + CurseMagicHit + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}