//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.initialRoleAttrieBase
{
   
public partial class TbInitialRoleAttrieBase
{
    private readonly Dictionary<int, initialRoleAttrieBase.InitialRoleAttrie> _dataMap;
    private readonly List<initialRoleAttrieBase.InitialRoleAttrie> _dataList;
    
    public TbInitialRoleAttrieBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, initialRoleAttrieBase.InitialRoleAttrie>();
        _dataList = new List<initialRoleAttrieBase.InitialRoleAttrie>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            initialRoleAttrieBase.InitialRoleAttrie _v;
            _v = initialRoleAttrieBase.InitialRoleAttrie.DeserializeInitialRoleAttrie(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, initialRoleAttrieBase.InitialRoleAttrie> DataMap => _dataMap;
    public List<initialRoleAttrieBase.InitialRoleAttrie> DataList => _dataList;

    public initialRoleAttrieBase.InitialRoleAttrie GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public initialRoleAttrieBase.InitialRoleAttrie Get(int key) => _dataMap[key];
    public initialRoleAttrieBase.InitialRoleAttrie this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}