//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.EnemyModelBase
{
/// <summary>
/// 技能回合参数
/// </summary>
public sealed partial class SkillValue :  Bright.Config.BeanBase 
{
    public SkillValue(ByteBuf _buf) 
    {
        PassSkill = _buf.ReadInt();
        ActiveSkill = _buf.ReadInt();
        PostInit();
    }

    public static SkillValue DeserializeSkillValue(ByteBuf _buf)
    {
        return new Tb.EnemyModelBase.SkillValue(_buf);
    }

    /// <summary>
    /// 被动技能ID
    /// </summary>
    public int PassSkill { get; private set; }
    /// <summary>
    /// 主动技能ID
    /// </summary>
    public int ActiveSkill { get; private set; }

    public const int __ID__ = -670903620;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PassSkill:" + PassSkill + ","
        + "ActiveSkill:" + ActiveSkill + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}