//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.enemyModelBase
{
   
public partial class TbEnemyModelBase
{
    private readonly Dictionary<int, enemyModelBase.EnemyModel> _dataMap;
    private readonly List<enemyModelBase.EnemyModel> _dataList;
    
    public TbEnemyModelBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, enemyModelBase.EnemyModel>();
        _dataList = new List<enemyModelBase.EnemyModel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            enemyModelBase.EnemyModel _v;
            _v = enemyModelBase.EnemyModel.DeserializeEnemyModel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, enemyModelBase.EnemyModel> DataMap => _dataMap;
    public List<enemyModelBase.EnemyModel> DataList => _dataList;

    public enemyModelBase.EnemyModel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemyModelBase.EnemyModel Get(int key) => _dataMap[key];
    public enemyModelBase.EnemyModel this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}