//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.item1
{
   
public partial class TbItem1
{
    private readonly Dictionary<int, item1.Item1> _dataMap;
    private readonly List<item1.Item1> _dataList;
    
    public TbItem1(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, item1.Item1>();
        _dataList = new List<item1.Item1>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            item1.Item1 _v;
            _v = item1.Item1.DeserializeItem1(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, item1.Item1> DataMap => _dataMap;
    public List<item1.Item1> DataList => _dataList;

    public item1.Item1 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item1.Item1 Get(int key) => _dataMap[key];
    public item1.Item1 this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}