//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.enemySpine
{
public sealed partial class EnemySpine :  Bright.Config.BeanBase 
{
    public EnemySpine(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EnemyName = _buf.ReadString();
        SpineResName = _buf.ReadString();
        PixelResName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AnimationName = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); AnimationName.Add(_e0);}}
        PostInit();
    }

    public static EnemySpine DeserializeEnemySpine(ByteBuf _buf)
    {
        return new enemySpine.EnemySpine(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 怪物名字
    /// </summary>
    public string EnemyName { get; private set; }
    /// <summary>
    /// Spine动画资源
    /// </summary>
    public string SpineResName { get; private set; }
    /// <summary>
    /// 像素动画资源
    /// </summary>
    public string PixelResName { get; private set; }
    /// <summary>
    /// 动画名称
    /// </summary>
    public System.Collections.Generic.List<string> AnimationName { get; private set; }

    public const int __ID__ = -1248811026;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EnemyName:" + EnemyName + ","
        + "SpineResName:" + SpineResName + ","
        + "PixelResName:" + PixelResName + ","
        + "AnimationName:" + Bright.Common.StringUtil.CollectionToString(AnimationName) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}