//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.equipment
{ 
    public enum EquipmentFlag
    {
        /// <summary>
        /// 大剑武器类型
        /// </summary>
        Sword = 1,
        /// <summary>
        /// 护肩防具类型
        /// </summary>
        Arm = 2,
        /// <summary>
        /// 胸甲防具类型
        /// </summary>
        Armor = 3,
        /// <summary>
        /// 护盾防具类型
        /// </summary>
        ShIeId = 4,
        /// <summary>
        /// 头盔防具类型
        /// </summary>
        Helmet = 5,
        /// <summary>
        /// 护肩防具类型
        /// </summary>
        Shoulder = 6,
        /// <summary>
        /// 鞋子防具类型
        /// </summary>
        Foot = 7,
        /// <summary>
        /// 护腿防具类型
        /// </summary>
        Leg = 8,
    }

} 
