//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.equipment
{
public sealed partial class EquipmentAttribute :  Bright.Config.BeanBase 
{
    public EquipmentAttribute(ByteBuf _buf) 
    {
        AttriId = _buf.ReadInt();
        Value = _buf.ReadInt();
        PostInit();
    }

    public static EquipmentAttribute DeserializeEquipmentAttribute(ByteBuf _buf)
    {
        return new equipment.EquipmentAttribute(_buf);
    }

    /// <summary>
    /// 装备属性值,0:生命值,1:MP,2:攻击力,3防御力
    /// </summary>
    public int AttriId { get; private set; }
    /// <summary>
    /// 属性值
    /// </summary>
    public int Value { get; private set; }

    public const int __ID__ = -1304267474;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AttriId:" + AttriId + ","
        + "Value:" + Value + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}