//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Tb.NpcConfigBase
{
/// <summary>
/// 对话文本列表
/// </summary>
public sealed partial class TalkMessageList :  Bright.Config.BeanBase 
{
    public TalkMessageList(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TalkArray = new System.Collections.Generic.List<Tb.NpcConfigBase.TalkMessage>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Tb.NpcConfigBase.TalkMessage _e0;  _e0 = Tb.NpcConfigBase.TalkMessage.DeserializeTalkMessage(_buf); TalkArray.Add(_e0);}}
        PostInit();
    }

    public static TalkMessageList DeserializeTalkMessageList(ByteBuf _buf)
    {
        return new Tb.NpcConfigBase.TalkMessageList(_buf);
    }

    /// <summary>
    /// 对话数组
    /// </summary>
    public System.Collections.Generic.List<Tb.NpcConfigBase.TalkMessage> TalkArray { get; private set; }

    public const int __ID__ = 884447839;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in TalkArray) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in TalkArray) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "TalkArray:" + Bright.Common.StringUtil.CollectionToString(TalkArray) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}