//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace GameConfig
{ 
   
public sealed partial class Tables
{
    public item.TbItem TbItem {get; }
    public equipment.TbEquipment TbEquipment {get; }
    public itemBackGround.TbItemBgGround TbItemBgGround {get; }
    public enemySpine.TbEnemySpine TbEnemySpine {get; }
    public enemyConfig.TbEnemyConfig TbEnemyConfig {get; }

    public Tables(System.Func<string, ByteBuf> idxLoader, System.Func<string, ByteBuf> dataLoader)
    {
        //var tables = new System.Collections.Generic.Dictionary<string, object>();
        //TbItem = new item.TbItem(idxLoader("item_tbitem")); 
        //tables.Add("item.TbItem", TbItem);
        //TbEquipment = new equipment.TbEquipment(loader("equipment_tbequipment")); 
        //tables.Add("equipment.TbEquipment", TbEquipment);
        //TbItemBgGround = new itemBackGround.TbItemBgGround(loader("itembackground_tbitembgground")); 
        //tables.Add("itemBackGround.TbItemBgGround", TbItemBgGround);
        //TbEnemySpine = new enemySpine.TbEnemySpine(loader("enemyspine_tbenemyspine")); 
        //tables.Add("enemySpine.TbEnemySpine", TbEnemySpine);
        //TbEnemyConfig = new enemyConfig.TbEnemyConfig(loader("enemyconfig_tbenemyconfig")); 
        //tables.Add("enemyConfig.TbEnemyConfig", TbEnemyConfig);
        //PostInit();

        //TbItem.Resolve(tables); 
        //TbEquipment.Resolve(tables); 
        //TbItemBgGround.Resolve(tables); 
        //TbEnemySpine.Resolve(tables); 
        //TbEnemyConfig.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TbEquipment.TranslateText(translator); 
        TbItemBgGround.TranslateText(translator); 
        TbEnemySpine.TranslateText(translator); 
        TbEnemyConfig.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}