//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.NpcConfigBase
{
public sealed partial class NpcConfig :  Bright.Config.BeanBase 
{
    public NpcConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NpcName = _buf.ReadString();
        Description = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TaskID = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TaskID.Add(_e0);}}
        TalkParam = Tb.NpcConfigBase.TalkMessageList.DeserializeTalkMessageList(_buf);
        PostInit();
    }

    public static NpcConfig DeserializeNpcConfig(ByteBuf _buf)
    {
        return new NpcConfigBase.NpcConfig(_buf);
    }

    /// <summary>
    /// NpcID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// Npc名称
    /// </summary>
    public string NpcName { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Description { get; private set; }
    /// <summary>
    /// 任务组
    /// </summary>
    public System.Collections.Generic.List<int> TaskID { get; private set; }
    /// <summary>
    /// 对话组
    /// </summary>
    public Tb.NpcConfigBase.TalkMessageList TalkParam { get; private set; }

    public const int __ID__ = -1483569463;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        TalkParam?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        TalkParam?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NpcName:" + NpcName + ","
        + "Description:" + Description + ","
        + "TaskID:" + Bright.Common.StringUtil.CollectionToString(TaskID) + ","
        + "TalkParam:" + TalkParam + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}