//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.NpcConfigBase
{
   
public partial class TBNpcConfigBase
{
    private readonly Dictionary<int, NpcConfigBase.NpcConfig> _dataMap;
    private readonly List<NpcConfigBase.NpcConfig> _dataList;
    
    public TBNpcConfigBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, NpcConfigBase.NpcConfig>();
        _dataList = new List<NpcConfigBase.NpcConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            NpcConfigBase.NpcConfig _v;
            _v = NpcConfigBase.NpcConfig.DeserializeNpcConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, NpcConfigBase.NpcConfig> DataMap => _dataMap;
    public List<NpcConfigBase.NpcConfig> DataList => _dataList;

    public NpcConfigBase.NpcConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public NpcConfigBase.NpcConfig Get(int key) => _dataMap[key];
    public NpcConfigBase.NpcConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}