//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.enemyConfig
{ 

public sealed partial class TbEnemyConfig
{
    private readonly Dictionary<int, enemyConfig.EnemyConfig> _dataMap;
    private readonly List<enemyConfig.EnemyConfig> _dataList;
    
    public TbEnemyConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<int, enemyConfig.EnemyConfig>();
        _dataList = new List<enemyConfig.EnemyConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = enemyConfig.EnemyConfig.DeserializeEnemyConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, enemyConfig.EnemyConfig> DataMap => _dataMap;
    public List<enemyConfig.EnemyConfig> DataList => _dataList;

    public enemyConfig.EnemyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemyConfig.EnemyConfig Get(int key) => _dataMap[key];
    public enemyConfig.EnemyConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}