//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.ATTACK
{ 
    [System.Flags]
    public enum RANGE
    {
        /// <summary>
        /// 单人
        /// </summary>
        SOLO = 1,
        /// <summary>
        /// 十字
        /// </summary>
        CROSS = 2,
        /// <summary>
        /// 某方全部
        /// </summary>
        ALL = 3,
        /// <summary>
        /// 游戏全屏
        /// </summary>
        ALL_REAL = 4,
        /// <summary>
        /// 自身
        /// </summary>
        SELF = 5,
    }

} 
