//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.itemBackGround1
{
public sealed partial class ItemBgGround :  Bright.Config.BeanBase 
{
    public ItemBgGround(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemBoxLine = _buf.ReadString();
        ItemColor = _buf.ReadString();
        PostInit();
    }

    public static ItemBgGround DeserializeItemBgGround(ByteBuf _buf)
    {
        return new itemBackGround1.ItemBgGround(_buf);
    }

    /// <summary>
    /// 品质ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 物品背景线框
    /// </summary>
    public string ItemBoxLine { get; private set; }
    /// <summary>
    /// 物品背景颜色
    /// </summary>
    public string ItemColor { get; private set; }

    public const int __ID__ = -430099427;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ItemBoxLine:" + ItemBoxLine + ","
        + "ItemColor:" + ItemColor + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}