//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.enemySpine
{ 

public sealed partial class EnemySpine :  Bright.Config.BeanBase 
{
    public EnemySpine(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["EnemyName"].IsString) { throw new SerializationException(); }  EnemyName = _json["EnemyName"]; }
        { if(!_json["SpineResName"].IsString) { throw new SerializationException(); }  SpineResName = _json["SpineResName"]; }
        { var __json0 = _json["AnimationName"]; if(!__json0.IsArray) { throw new SerializationException(); } AnimationName = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  AnimationName.Add(__v0); }   }
        PostInit();
    }

    public EnemySpine(int id, string EnemyName, string SpineResName, System.Collections.Generic.List<string> AnimationName ) 
    {
        this.Id = id;
        this.EnemyName = EnemyName;
        this.SpineResName = SpineResName;
        this.AnimationName = AnimationName;
        PostInit();
    }

    public static EnemySpine DeserializeEnemySpine(JSONNode _json)
    {
        return new enemySpine.EnemySpine(_json);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 怪物名字
    /// </summary>
    public string EnemyName { get; private set; }
    /// <summary>
    /// 怪物动画资源
    /// </summary>
    public string SpineResName { get; private set; }
    /// <summary>
    /// 动画名称
    /// </summary>
    public System.Collections.Generic.List<string> AnimationName { get; private set; }

    public const int __ID__ = -1248811026;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EnemyName:" + EnemyName + ","
        + "SpineResName:" + SpineResName + ","
        + "AnimationName:" + Bright.Common.StringUtil.CollectionToString(AnimationName) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
