//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.enemySpine
{ 

public sealed partial class TbEnemySpine
{
    private readonly Dictionary<int, enemySpine.EnemySpine> _dataMap;
    private readonly List<enemySpine.EnemySpine> _dataList;
    
    public TbEnemySpine(JSONNode _json)
    {
        _dataMap = new Dictionary<int, enemySpine.EnemySpine>();
        _dataList = new List<enemySpine.EnemySpine>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = enemySpine.EnemySpine.DeserializeEnemySpine(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, enemySpine.EnemySpine> DataMap => _dataMap;
    public List<enemySpine.EnemySpine> DataList => _dataList;

    public enemySpine.EnemySpine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemySpine.EnemySpine Get(int key) => _dataMap[key];
    public enemySpine.EnemySpine this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}