//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameConfig.equipment
{ 
    public enum EquipmentFlag
    {
        /// <summary>
        /// 大剑武器类型
        /// </summary>
        Sword = 1,
        /// <summary>
        /// 斧头武器类型
        /// </summary>
        Axe = 2,
        /// <summary>
        /// 弓箭武器类型
        /// </summary>
        Bow = 3,
        /// <summary>
        /// 法杖武器类型
        /// </summary>
        Wand = 4,
        /// <summary>
        /// 护手防具类型
        /// </summary>
        Arm = 5,
        /// <summary>
        /// 胸甲防具类型
        /// </summary>
        Armor = 6,
        /// <summary>
        /// 护盾防具类型
        /// </summary>
        ShIeId = 7,
        /// <summary>
        /// 头盔防具类型
        /// </summary>
        Helmet = 8,
        /// <summary>
        /// 护肩防具类型
        /// </summary>
        Shoulder = 9,
        /// <summary>
        /// 鞋子防具类型
        /// </summary>
        Foot = 10,
    }

} 
