//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace GameConfig.equipment
{ 

public sealed partial class TbEquipment
{
    private readonly Dictionary<int, equipment.Equipment> _dataMap;
    private readonly List<equipment.Equipment> _dataList;
    
    public TbEquipment(JSONNode _json)
    {
        _dataMap = new Dictionary<int, equipment.Equipment>();
        _dataList = new List<equipment.Equipment>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = equipment.Equipment.DeserializeEquipment(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, equipment.Equipment> DataMap => _dataMap;
    public List<equipment.Equipment> DataList => _dataList;

    public equipment.Equipment GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public equipment.Equipment Get(int key) => _dataMap[key];
    public equipment.Equipment this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}