//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.PassSkillBase
{
public sealed partial class Attribute :  Bright.Config.BeanBase 
{
    public Attribute(ByteBuf _buf) 
    {
        AttriId = _buf.ReadInt();
        Value = _buf.ReadInt();
        Percent = _buf.ReadInt();
        PostInit();
    }

    public static Attribute DeserializeAttribute(ByteBuf _buf)
    {
        return new PassSkillBase.Attribute(_buf);
    }

    /// <summary>
    /// 技能属性值,对应单位属性表
    /// </summary>
    public int AttriId { get; private set; }
    /// <summary>
    /// 属性值
    /// </summary>
    public int Value { get; private set; }
    /// <summary>
    /// 0:不是百分比,1:是百分比
    /// </summary>
    public int Percent { get; private set; }

    public const int __ID__ = 148521055;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AttriId:" + AttriId + ","
        + "Value:" + Value + ","
        + "Percent:" + Percent + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}